### PR TITLE
Change RespawnSeconds & RespawnBossSeconds from 10 to 0

### PR DESCRIPTION
**Pull request by moisterrific**
This way it will use the game's timers. I tested on a master world, setting them both to 0 will just make the respawn default to 15s normally and 30s for bosses. So I would assume it will also use whatever the default time is on lower difficulties.

### CODE REVIEW

**Review by iamyou — APPROVED** [review]

**Review by iamyou — DISMISSED** [review]
I found players will respawn faster than expected in expert mode

**Comment by moisterrific** [comment]
> I found players will respawn faster than expected in expert mode

is this with the existing 10s values or with my proposed 0s?

**Comment by QuiCM** [comment]
So to summarize
* Less than vanilla time works
* More than vanilla time doesn't work (not sure what happens though)
* 0 makes it vanilla time?

**Comment by moisterrific** [comment]
> Less than vanilla time works

Yes

> More than vanilla time doesn't work (not sure what happens though)

I think it just defaults to the max possible timer in vanilla? (15s normal, 30s bosses, master difficulty) Don't remember if TShock will force respawn you again when it hits 40s though if you set the time to that.

> 0 makes it vanilla time?

That's what I found out from setting it to 0, I was just curious what would happen and played around w/ the setting. Turns out 1s is the lowest possible time you can have, 0 somehow defaults to vanilla timers.

**Review by hakusaro — DISMISSED** [review]
I raised it to 10s to stop desync. I don't see any evidence to support changing this to 0 by default. Can you provide videos that demonstrate the exact behavior when set to 0 and why this is better than not?

**Comment by moisterrific** [comment]
> 
> 
> I raised it to 10s to stop desync. I don't see any evidence to support changing this to 0 by default. Can you provide videos that demonstrate the exact behavior when set to 0 and why this is better than not?

You can test it out yourself if you have any doubts, 0s somehow "just works".  Using the game default respawn countdown is better because it's adaptive to the world difficulty instead of a static 10s. The countdown varies depending on difficulty, so 10s only works if you're playing on journey/classic, meanwhile expert/master is 15 and 30 for bosses.

(also the 0s way does not have any desync issue)

**Comment by hakusaro** [comment]
I'm changing my review to _abstain._

**Review by hakusaro — APPROVED** [review]
lgtm_7

**Review by QuiCM — APPROVED** [review]
This is probably worthwhile. Keeping vanilla things where possible & augmenting where desired is a good path to take

**Comment by QuiCM** [comment]
@moisterrific merge conflicts :(

**Comment by moisterrific** [comment]
i can't easily resolve the merge conflict on my end like i could before, im guessing it's because i deleted a prev fork of tshock i forked from chi-rei-den/axeelander since on top here it shows the patch no longer exists

image

i think what i'll do is just close this one and make a new commit with the same changes since it's such a small change

**Comment by moisterrific** [comment]
See new: https://github.com/Pryaxis/TShock/pull/2450

**Pull request closed without merging**
