### PR TITLE
Added 1.4.1.0 player inflicted debuffs to bouncer

### PR DESCRIPTION
**Pull request by Quinci135**
OnFire3/Hellfire - New magma stone debuff that deals 15 dps instead of 4 dps
Frostburn2/Frostbite - Frost armor new set bonus 25 dps instead of 8 dps
BoneWhipNPCDebuff - Debuff applied from new Spinal Tap whip

### CODE REVIEW

**Comment by Quinci135** [comment]
afaik tsapi has been updated https://github.com/Pryaxis/TerrariaAPI-Server/pull/182 so those buffid definitions should be in place

**Comment by QuiCM** [comment]
You'll need to update the submodule as well to get the latest tsapi changes

**Comment by hakusaro** [comment]
Hi! xoxo! Can you go here and complete the onboarding steps? https://github.com/sponsors

Or link applicable source of income?

P.S. we will flag this with hacktoberfest tags too, when accepted.

**Comment by Quinci135** [comment]
Thanks, but it's just one pull request of a few lines nor did either of those draw me here

**Comment by QuiCM** [comment]
Going to hold this one here until TSAPI for 1.4.1.1 is committed

**Review by QuiCM — APPROVED** [review]
LGTM

**Pull request merged**
