### PR TITLE
[WIP]Fragments: Separate out Server-Side-Character

### PR DESCRIPTION
**Pull request by AxeelAnder**
[Issue #1563](https://github.com/Pryaxis/TShock/issues/1563)

### CODE REVIEW

**Comment by AxeelAnder** [comment]
Should 'CharacterDB' and 'PlayerData' be components of this subsystem?
PlayerData is widely used in many things, if it's a part of this, ssc will be indispensable.

**Comment by ivanbiljan** [comment]
@AxeelAnder are you still working on this? As far as your previous question goes; yes, those files should be a part of the SSC subsystem imo (given that they handle SSC data).

**Comment by AxeelAnder** [comment]
Give up. It's too hard for me, I have no enough experience or talent on software architecture design.

**Comment by QuiCM** [comment]
Hi, I'm going to reopen this for visibility so it hopefully doesn't get forgotten next time one of the team has capacity for development

**Comment by hakusaro** [comment]
@AxeelAnder hi, I think you're very talented xoxo

**Comment by AxeelAnder** [comment]
@QuiCM started his work in https://github.com/Pryaxis/TShock/pull/1982, so pls let me close this pr, it's my kurorekishi :sob:

**Pull request closed without merging**
