### PR TITLE
Bouncer OnTileEdit - Remove person storage tile check for SSC

### PR DESCRIPTION
**Pull request by Patrikkk**
We do not allow piggybank and safe to be placed if SSC is enabled.
The DefendersFroge and VoidVault have the same functionality as far as I know. So adding these two missing tiles.

### CODE REVIEW

**Comment by kevzhao2** [comment]
Why do we disallow these tiles? Now that piggy bank/safe are synced with the server, it should be okay to actually delete the entire check.

**Comment by QuiCM** [comment]
We no longer need to disable these tiles

**Review by QuiCM — CHANGES_REQUESTED** [review]
We no longer need to disable these tiles

**Comment by Patrikkk** [comment]
Thanks for the info guys! 
Want another commit to remove that check? Should I kill the List of personalStorage as well?

**Comment by QuiCM** [comment]
> 
> 
> Thanks for the info guys!
> Want another commit to remove that check? Should I kill the List of personalStorage as well?

Yes please and yes please. I'll update the PR title :)

**Comment by Patrikkk** [comment]
Sent:)

**Review by QuiCM — APPROVED** [review]

**Pull request merged**
