### PR TITLE
Fix flamethrowers kicking players

### LINKED ISSUE #2729: Using the Flamethrower weapon kicks players for abnormally added buff.
* TShock version: TShock.5.0.0-beta.0.5
* TShock build number (if known): 699dbf9

#### Reproduction steps (if applicable)?

Reproduced by damaging any enemy with the Flamethrower.

#### Any stack traces or error messages (if known)?

```
GetDataHandlers / HandlePlayerBuffList handled event and sent data Marotheit
```

[Server Log.log](https://github.com/Pryaxis/TShock/files/9807438/2022-10-18_01-11-43.log)

#### What plugins and what versions of those plugins are you running?

None, except TShock itself.

### PR DESCRIPTION
**Pull request by instant-segfault**
Fixes #2729

### CODE REVIEW

**Review by hakusaro — APPROVED** [review]

**Comment by hakusaro** [comment]
@BashGuy10 thank you so much for your contributions! I really appreciate your hard work! <3

**Comment by hakusaro** [comment]
@BashGuy10 I just realized -- you have vigilant mode on. Your commit is unsigned. Can you either sign your commit or turn off vigilant mode?
Screen Shot 2022-10-22 at 17 20 18

**Comment by hakusaro** [comment]
See: https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits

**Comment by instant-segfault** [comment]
I don't know what that did, but it seems to have worked?..(probably should've disabled vigilant instead)

**Comment by hakusaro** [comment]
@BashGuy10 all good! Shipping!

**Pull request merged**
