### PR TITLE
Replace /godmode with Journey mode's godmode

### LINKED ISSUE #2209: Replace current Godmode (Healmode) with Journey mode Godmode
**Is your feature request related to a problem? Please describe.**
It's not related to a problem.
**Describe the solution you'd like**
Instead of continue using the inconsistent annoying healmode, implement actual journey mode godmode.
**Describe alternatives you've considered**
No alternative solution.
**Additional context**
No, it's not impossible because Quake already managed to do but refuses to share it.

### PR DESCRIPTION
**Pull request by Stealownz**
Closes #2209

### CODE REVIEW

**Comment by Stealownz** [comment]
Important side-effect changes:
If a player has Journey godmode set enabled in local save and **does not** have permission `tshock.journey.godmode`,
when player joins the server will reject and broadcast send to disable Journey godmode.
They will also see the message "You are not allowed to toggle godmode"

However, if a player with Journey godmode set enabled in local save and **has** the permission `tshock.journey.godmode`,
then player will keep the Journey godmode state on join.
Note that this behavior is changed from TShock's godhealmode, which is always default false on player join

**Comment by QuiCM** [comment]
Based on discussion in Discord, implementation LGTM. Has this been tested for any gotchas?

**Comment by Stealownz** [comment]
Yes, tested two cases:

Tested for player with Journey godmode enabled in local save on join, see previous comment.

Tested for player joining into the index slot of a previous player with godmode enabled.
Issue: if a player in index slot 2 enables godmode then disconnects, another player who connects into index slot 2 is still considered godmode to the server and other players.
Expected behavior: the other player should not be godmode since it did not request to be godmode, and was not godmode enabled in the first place.
Solution: send disable godmode when player leaves if they were godmode,
and also check if player does not have permission, then reject and send a disable godmode

**Comment by Stealownz** [comment]
Closing PR, found other creative powers also require handling on leave/join due to client/server mismatch on enabled states.
Will test and fix first

**Pull request closed without merging**
