### PR TITLE
Add ban usage examples + minor grammar & visual fixes for ban help

### PR DESCRIPTION
**Pull request by moisterrific**
Added usage examples for:
- banning offline player by account
- banning offline player by ip
- banning online player by index

Added ban help examples after ban help commands and fixed a few minor visual/grammar issues relating to ban help

Looks something like this in-game: 
Terraria_2021_07_25_22_35_12_250

### CODE REVIEW

**Review by bartico6 — CHANGES_REQUESTED** [review]
I know I'll sound like I have a stick up my arse for saying this, but I'm not sure if one should be referencing their own nickname or name in examples for commands. I'd personally use as abstract and as unrelated playernames ('Joe' or something) as possible.

cc @hakusaro on that, everything else looks good conceptually :-)

**Comment by moisterrific** [comment]
> I know I'll sound like I have a stick up my arse for saying this, but I'm not sure if one should be referencing their own nickname or name in examples for commands. I'd personally use as abstract and as unrelated playernames ('Joe' or something) as possible.
> 
> 
> 
> cc @hakusaro on that, everything else looks good conceptually :-)

i agree, when i first saw the current ban examples i thought seeing my own char's name was a bit weird. For these im just following the trend set out by who/whomever first wrote it

**Comment by QuiCM** [comment]
> 
> 
> I know I'll sound like I have a stick up my arse for saying this, but I'm not sure if one should be referencing their own nickname or name in examples for commands. I'd personally use as abstract and as unrelated playernames ('Joe' or something) as possible.
> 
> cc @hakusaro on that, everything else looks good conceptually :-)

It uses `args.Player.Account` - I figured seeing their own account name would be more recognizable (and protect all the poor Joes of the world from feeling vilified 😢). However we're not consistent with this anywhere so it is open to change

**Review by QuiCM — DISMISSED** [review]

**Review by bartico6 — DISMISSED** [review]
Oh dear it shows you your own account, I really didn't notice that in code and thought it hardcodes into 'stacey'.

In that case I retract my previous statement and it's good to merge.

**Review by QuiCM — APPROVED** [review]

**Pull request merged**
