### PR TITLE
Rest removal (#1588, part 1) [WIP]

### PR DESCRIPTION
**Pull request by aylinni-empyrea**
- [x] Remove REST from TShock
- [ ] Complete redesigned plugin and add a link for it in changelog (?)

This PR removes all traces of REST from the main codebase, which later will be ported over a separate plugin. (for #1588)

(also removed Group.ParentName as its comment stated it was added for rest, can add it back if need be)

### CODE REVIEW

**Review by hakusaro — APPROVED** [review]
The removal part looks good.

**Review by QuiCM — APPROVED** [review]

**Comment by AxeelAnder** [comment]
I'm going to do this for current httpserver lib is not .netstd.

**Comment by hakusaro** [comment]
I suspect this won't get completed. If it will, please re-open.

**Comment by QuiCM** [comment]
> I suspect this won't get completed. If it will, please re-open.

I intend to do this with the DI refactor & uplift to .NET hosted services. Happy for this to remain closed

**Pull request closed without merging**
