### PR TITLE
Add door debug visualizer to Bouncer

### PR DESCRIPTION
**Pull request by hakusaro**
This is my own take on a STS debug visualizer. It pads and prints things
nicely so that it looks like the game representation and might be
helpful for other people. Obviously this is like very low priority, but
I wanted to save it off in the event that someone other than me likes
it.

It looks like this:
Screen Shot 0002-05-31 at 00 00 24

It shows the current server state as well as the new server state after the change and highlights doors as open spaces with curly braces indicating that the door is "active."

### CODE REVIEW

**Comment by QuiCM** [comment]
I like this, but I'm not sure I'm a fan of the symbols marking the door.
Not sure what `[ ]` or `{ }` represents

**Comment by hakusaro** [comment]
@QuiCM it's supposed to be an "open gap" e.g., `[ ]` is an open door, and `{ }` is an open active door and `[x]` is a "filled in" door (a closed door). I can remove those if you want though, if doors don't need debugging anymore.

**Comment by QuiCM** [comment]
> 
> 
> @QuiCM it's supposed to be an "open gap" e.g., `[ ]` is an open door, and `{ }` is an open active door and `[x]` is a "filled in" door (a closed door). I can remove those if you want though, if doors don't need debugging anymore.

for clarity my preference would be to remove it or have a legend explaining what special symbols mean

**Comment by hakusaro** [comment]
> for clarity my preference would be to remove it or have a legend explaining what special symbols mean

Ya, if you're at all interested I can change it to not do that. I'm not sure if it would help with other STS debugging things though, because it doesn't show all of the different attributes on a square's state changes.

**Comment by hakusaro** [comment]
(Maybe better suited to packet monitor honestly)

**Comment by hakusaro** [comment]
Sorry to triple post, but another easy thing could just be to not handle the event and then return without sending anything either. I did at least go through and deduce that the STS event isn't worth messing with (it changes nothing about the state of the world), and flag it off so that it's not going to enter a fall through state if a user were to send a door change to bypass all other STS checks.

**Comment by hakusaro** [comment]
@QuiCM it's kinda still messy but I think it's still novel (iterates y before x, writes in nice lines, pads for fixed widths)

**Review by QuiCM — APPROVED** [review]

**Comment by QuiCM** [comment]
I pulled a sneaky and pushed this in with #1965

**Comment by hakusaro** [comment]
@QuiCM :D

**Pull request closed without merging**
