### PR TITLE
.NetCore

### PR DESCRIPTION
**Pull request by AxeelAnder**
- [x] Simplify build pipeline
- [x] CI(Github Action)
- [x] CI(AppVeyor)
- [ ] Build instruction
- [ ] Add doc

### CODE REVIEW

**Comment by hakusaro** [comment]
I converted your pr to a github draft -- we'll probably pull the plug on the wip bot now that you can convert PRs to and from draft status from within github (and it's cooler that way)

**Comment by hakusaro** [comment]
I would honestly prefer getting this done before a 1.4 patch because doing that would get us in better shape in terms of converting something working to something ready for release. @QuiCM is working on some stuff and needs to know if we’re going to be on .NET Core or not to do the work.

**Comment by AxeelAnder** [comment]
> I would honestly prefer getting this done before a 1.4 patch because doing that would get us in better shape in terms of converting something working to something ready for release. @QuiCM is working on some stuff and needs to know if we’re going to be on .NET Core or not to do the work.

I'm re-thinking about how we get into .net core, yesterday I encountered more challenges on elegance brought by current architecture and backward compatibility and framework version requirements and many other things. If we just need a working version then it's almost there, otherwise it'd take a relative long period for us all to figure out solutions or make trades

**Comment by hakusaro** [comment]
Interesting, okay! Thank you for your research here!

**Comment by QuiCM** [comment]
> 
> 
> > I would honestly prefer getting this done before a 1.4 patch because doing that would get us in better shape in terms of converting something working to something ready for release. @QuiCM is working on some stuff and needs to know if we’re going to be on .NET Core or not to do the work.
> 
> I'm re-thinking about how we get into .net core, yesterday I encountered more challenges on elegance brought by current architecture and backward compatibility and framework version requirements and many other things. If we just need a working version then it's almost there, otherwise it'd take a relative long period for us all to figure out solutions or make trades

What does working version entail?
What would backwards compat etc look like?

I'm of the opinion that if we can get the OTAPI + TSAPI stack running on netcore, then we can rework TShock until it also works. We have other major breaking changes in the pipeline right now that will require everyone to upgrade their plugins, so I don't see a reason why we can't take this opportunity to get as much done as possible

**Comment by AxeelAnder** [comment]
> > > I would honestly prefer getting this done before a 1.4 patch because doing that would get us in better shape in terms of converting something working to something ready for release. @QuiCM is working on some stuff and needs to know if we’re going to be on .NET Core or not to do the work.
> > 
> > 
> > I'm re-thinking about how we get into .net core, yesterday I encountered more challenges on elegance brought by current architecture and backward compatibility and framework version requirements and many other things. If we just need a working version then it's almost there, otherwise it'd take a relative long period for us all to figure out solutions or make trades
> 
> What does working version entail?
> What would backwards compat etc look like?
> 
> I'm of the opinion that if we can get the OTAPI + TSAPI stack running on netcore, then we can rework TShock until it also works. We have other major breaking changes in the pipeline right now that will require everyone to upgrade their plugins, so I don't see a reason why we can't take this opportunity to get as much done as possible

If breaking changes are acceptable, it'll be a lot easier.

**Comment by hakusaro** [comment]
Screenshot from 2020-05-13 22-15-52
Screenshot from 2020-05-13 22-16-32

May want to clarify the directory structure here since I'm not sure where to put the large collection of DLLs. Edit: This was the linux 64 release too.

**Comment by AxeelAnder** [comment]
Do you mind replacing logger with third-party logging lib?

**Comment by hakusaro** [comment]
Screenshot from 2020-05-13 22-53-30

omg it works

> Do you mind replacing logger with third-party logging lib?

I don't. @QuiCM do you?

**Comment by AxeelAnder** [comment]
I feel hard to write build instruction, can anyone familiar with macos or unix help me out?
Basically build is `dotnet build [sln|proj]`, the only trouble is otapi patcher doesn't support .net core, so we need mono to run it.

**Comment by QuiCM** [comment]
> 
> 
> Screenshot from 2020-05-13 22-53-30
> 
> omg it works
> 
> > Do you mind replacing logger with third-party logging lib?
> 
> I don't. @QuiCM do you?

Nope. Go for it

**Comment by AxeelAnder** [comment]
As the .netcore binaries are out of the box, I think there's no need to write additional docs.

**Comment by AxeelAnder** [comment]
btw, @hakusaro we don't need appveyor building script any more, TShock.sln can be directly compiled in this branch

**Comment by AxeelAnder** [comment]
Taking patches development into consideration, I added a local otapi configuration, enabling it projects will use local otapi patched by local patches

And as the result, I need to write a more thorough build instruction

**Comment by rhys-kitikion** [comment]
Is there more work still to do on this?  I would love to see this as part of the main branch, especially if its proven to be more stable than using mono for linux releases.  Is there a way I could test this without using a docker release?

**Comment by AxeelAnder** [comment]
> Is there more work still to do on this? I would love to see this as part of the main branch, especially if its proven to be more stable than using mono for linux releases. Is there a way I could test this without using a docker release?

it's pending until stable tshock comes out. If orion is prepared before that, I will drop this pr(orion is .netcore only)

**Comment by mixels** [comment]
Any chance we can get this in a pre-release?

**Comment by mixels** [comment]
@AxeelAnder Getting the below error trying to run `TerrariaServer` from the most recent linux-x64-release artifact on Ubuntu. Limited research suggests this relates to the trim. Any ideas?

```
Failure processing application bundle.
Couldn't open host binary for reading contents
Segmentation fault (core dumped)
```

Edit: Interestingly, the win-x64-release artifact does work for me on Win10.
Edit 2: Also interesting, the any-x64-release artifact works for me on Ubuntu. Would love to see it nudged up to Terraria version 1.4.0.5 for further testing.

**Comment by mixels** [comment]
How is the current prerelease in terms of stability? Is this anywhere near ready to merge in?

**Comment by hakusaro** [comment]
@AxeelAnder heya hey, lots of people really want this merged -- any idea what's left?

**Comment by sgkoishi** [comment]
Will TShock have both net 5 (or core 3) and netfx release; or only one target will be maintained?

**Comment by bartico6** [comment]
> 
> 
> Will TShock have both net 5 (or core 3) and netfx release; or only one target will be maintained?

why would anyone maintain .netfx if .netcore runs everywhere .netfx and mono does, I'd wager it'll be only .netcore/.net5 maintained from here on out.

**Comment by ldilley** [comment]
This feature would be welcome as it will enable the Terracord plugin to reliably run under Linux/Unix.

**Comment by AxeelAnder** [comment]
I'll close this pr for it's outdated and wouldn't help to port TShock to coreclr yet

**Pull request closed without merging**
