### PR TITLE
Missing backtick from RegionManager Group table.

### PR DESCRIPTION
**Pull request by Patrikkk**
Group is a reserved keyword in MySQL 8. Requires backtick.
Missed this from previous commit. Version 8 would error on table creation.

### CODE REVIEW

**Comment by hakusaro** [comment]
Did you check to see if the server creates dB normally on SQLite with this?

**Comment by Patrikkk** [comment]
I checked now. It does create the table, but it fails to execute INSERT query.

**Comment by hakusaro** [comment]
What?

**Review by hakusaro — CHANGES_REQUESTED** [review]
Needs to be made to work.

**Review by hakusaro — APPROVED** [review]

**Pull request merged**
