### PR TITLE
Update Manager now uses TLS.

### PR DESCRIPTION
**Pull request by pandabear41**
Simple PR for Hacktoberfest.

Some things to change on your Cloudflare or I need to add code to allow the specific self-signed Cloudflare certificate. 

> * [x]  Need to configure cloudflare to use the Universal SSL cert. https://support.cloudflare.com/hc/en-us/articles/200170566-Why-isn-t-SSL-working-for-my-site- (@hakusaro)
> * [x]  Test code in Mono and .NET to see if it works or generates an HttpRequestException exception. (@pandabear41)

Solves issue #1633

### CODE REVIEW

**Comment by hakusaro** [comment]
Backstory: The reason why TLS on update.tshock.co wasn't working is because the certificate on that host is the CloudFlare origin certificate, which enables us to have encrypted connections to upstream CloudFlare servers, but not much else. The `update.tshock.co` endpoint was actually hitting the backend server directly, rather than going through CloudFlare at all, simply as a result of a quirk of our infrastructure. Since it's an API endpoint, the requests to it come in as obviously not browsers. This means that CloudFlare's automatic security system (which is set to high) would likely throw out these requests as they're obviously automated.

In order to disable the security system on a per app basis, we needed to add a page rule that would whitelist that subdomain. But we were all out of page rules until now -- when I realized that we had a page rule for a domain that was no longer in use. By removing that page rule, we were able to put `update.tshock.co` behind CloudFlare, allowing it to be proxied with TLS successfully.

screen shot 2018-10-02 at 20 18 07

**Comment by hakusaro** [comment]
@pandabear41 FYI: This works on Mono a-okay.

Tested on:

```
Mono JIT compiler version 5.4.1.6 (tarball Mon Dec 11 14:59:42 GMT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

**Comment by pandabear41** [comment]
Tested with .NET, no more unsigned cert exceptions.

**Comment by Ijwu** [comment]
Thanks for helping us out!

**Pull request merged**
