### PR TITLE
minor improvement to stock MOTD behavior

### PR DESCRIPTION
**Pull request by moisterrific**
Just in case users change the specifier, motd should also reflect any changes if they kept the `/help` line.

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
such a minor change so I didn't bother

### CODE REVIEW

**Review by QuiCM — DISMISSED** [review]

**Comment by moisterrific** [comment]
Also kinda want to change a bit on how motd looks out of the box.

proposed 
vs.
current

Terraria_2021_05_14_13_14_04_016 (2)

I want to get rid of using the color red since that's usually associated with warnings or error messages throughout TShock. 
I think using the same yellow for `%map%` as `%players%` bc many info messages and the periodic world saving msg broadcast also use this color. 
Also added some subtle gradients.

**Comment by QuiCM** [comment]
I don't see an image for 'proposed'

**Comment by bartico6** [comment]
> 
> 
> I don't see an image for 'proposed'

I think it's the first and second motd on the same image that is the proposed and current

**Comment by QuiCM** [comment]
> > I don't see an image for 'proposed'
> 
> I think it's the first and second motd on the same image that is the proposed and current

Oh yeah, you right. Thanks

**Review by QuiCM — APPROVED** [review]

**Review by hakusaro — APPROVED** [review]

**Pull request merged**
