### PR TITLE
Added a configuration option to suppress player chat messages in the server console

### PR DESCRIPTION
**Pull request by ACaiCat**
`"DisplayChatToServerConsole": true` (default value is true)
if it is set to `false`, player chat messages will not be displayed in the server console

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I would like to see a video on how it works...

**Comment by bartico6** [comment]
> I would like to see a video on how it works...

if the option is set to false, chat isn't printed in server console.

**Comment by ghost** [comment]
I never see chat printed on the console, i might have an inadequate version installed

**Comment by ACaiCat** [comment]
https://github.com/Pryaxis/TShock/assets/62058454/e1b6514c-7a94-49fb-8f31-915422f5dac6

**Review by ghost — APPROVED** [review]
This can decrease clutter in the server console if the server has multiple players in it and it (according to my test) decreases GPU use, i ran these tests on my devices and gave them out to each one in the house at the time... i still have these devices but it works well with the current version. I suggest a full review from a collaborator because i do not understand much about this code but this is a good and working modification.

**Comment by ghost** [comment]
@DaBomberNTG or @hakusaro please review this Pull Request as i have approved this... if there is an incorrection in my test then feel free to request changes as i will do a new test

**Pull request closed without merging**
