### PR TITLE
Add spawnpets perm to trustedadmin & owner

### PR DESCRIPTION
**Pull request by moisterrific**
Also fix a few formatting inconsistencies that was the result from editing on mobile

Is it necessary to update the changelog for a small edit like this?

### CODE REVIEW

**Review by QuiCM — CHANGES_REQUESTED** [review]
Yes please, changelog update would be good. Formatting seems to have an extra indent in there now btw

**Comment by moisterrific** [comment]
> 
> 
> Yes please, changelog update would be good. Formatting seems to have an extra indent in there now btw

Updated the changelog. For some reason the formatting showed the perms I added to require an extra indent but now it's indented too much smh

**Review by Patrikkk — APPROVED** [review]
lgtm

**Review by Patrikkk — APPROVED** [review]

**Comment by Patrikkk** [comment]
You might want to get Chris to re-review or try marking the change request as resolved.

**Review by QuiCM — APPROVED** [review]

**Comment by QuiCM** [comment]
Apologies for the delay. Thanks @moisterrific and @Patrikkk  :)

**Pull request merged**
