### PR TITLE
Bouncer OnTileEdit - Add tile replace action to tileban check.

### PR DESCRIPTION
**Pull request by Patrikkk**
Tiny change, but a pressing matter. My smallest PR ever? hahah.
Referencing #2017 , as this patches the tile replace bypass issue that is mentioned.

### CODE REVIEW

**Review by hakusaro — APPROVED** [review]
This looks great! Can you also update these checks, because they're related to updating thresholds?
* https://github.com/Pryaxis/TShock/pull/2024/files#diff-3086bd09c54e93b5f9a34786586f710cL539
* https://github.com/Pryaxis/TShock/pull/2024/files#diff-3086bd09c54e93b5f9a34786586f710cR548

Your changes help enforce replacing tiles in terms of ban state, but it doesn't look like replacements are covered by TileKill/TilePlace thresholds. If you don't want to, I can happily merge this without them :)

**Comment by hakusaro** [comment]
Bah, those links are not good. There are two threshold checks in the same method -- TilePlaceThreshold and TileKillThreshold. Both deserve to be ticked and currently they only happen on Place/Kill events, not replace events.

**Comment by Patrikkk** [comment]
My bad:) I just quickly patched the issue that someone reported to me, I didn't look for any leftovers. 
The links didn't work indeed. I tried to spot the lines you mentioned, but not sure I got both.
At the same time, I didn't want to spam in redundant checks or ones that don't exactly make sense. 
I just sent another commit that adds two more checks. One is for tile Threshold. Other is for the maxtile check.
Aaand I'm sending another because I forgot to update changelog on this.

**Comment by hakusaro** [comment]
L548 is still needed, I think.

**Comment by Patrikkk** [comment]
Indeed, thank you:) That made me notice a few other checks regarding walls and tile killing.
Gotta be honest the checks in the method are quite badly documented, makes it hard to understand what some of them do. If I find time I might clean things up a bit.

**Pull request merged**
