### PR TITLE
Allow Torch God's Facor to place biome torch and campfire

### PR DESCRIPTION
**Pull request by sgkoishi**
https://github.com/Pryaxis/TShock/discussions/2783#discussioncomment-4070067

### CODE REVIEW

**Review by hakusaro — COMMENTED** [review]
Seems good, but the changelog has too many entries. Can you reduce the changelog to only things that have changed in this PR?

**Comment by sgkoishi** [comment]
Still two lines left but one of them is for #2809 controlled by the bot, would it be fine?

**Comment by hakusaro** [comment]
> Still two lines left but one of them is for https://github.com/Pryaxis/TShock/pull/2809 controlled by the bot, would it be fine?

eh?

**Comment by sgkoishi** [comment]
> > Still two lines left but one of them is for #2809 controlled by the bot, would it be fine?
> 
> eh?

The second line `Allowed Crystal Shard to grow` is for #2809 . Or maybe I just remove that line?

**Pull request merged**
