### PR TITLE
Add WorldInfo broadcast in /worldmode

### LINKED ISSUE #2332: Send WorldInfo in /worldmode
**Is your feature request related to a problem? Please describe.**
`/worldmode` doesn't send world info, so the players are desynced

**Describe the solution you'd like**
`/worldmode` should send world info

**Describe alternatives you've considered**
none

### PR DESCRIPTION
**Pull request by bartico6**
Fixes #2332

### CODE REVIEW

**Review by QuiCM — APPROVED** [review]

**Comment by bartico6** [comment]
For some reason, clicking two people in rapid succession will remove one of them as a reviewer....?

**Comment by hakusaro** [comment]
@bartico6 that’s because the plan/version of GitHub we’re on doesn’t support multiple requested reviewers

**Review by hakusaro — APPROVED** [review]

**Comment by bartico6** [comment]
That explains it. In hindsight pinging two people for something so tiny is a bit unnecessary anyway.

**Comment by hakusaro** [comment]
Technically speaking we usually wait for 2 reviews on everything, so it’s nbd

**Comment by hakusaro** [comment]
Actually hold that, I want to check something first

**Comment by bartico6** [comment]
> 
> 
> Technically speaking we usually wait for 2 reviews on everything, so it’s nbd

See, I had that subconscious idea from other PRs I witnessed, but still had second thoughts if I should be summoning two people for a change that's essentially 1 LoC.

> 
> 
> Actually hold that, I want to check something first

By all means! 👍

**Comment by hakusaro** [comment]
> See, I had that subconscious idea from other PRs I witnessed, but still had second thoughts if I should be summoning two people for a change that's essentially 1 LoC.

The rule of thumb is 2 people for external changes and 1 people for internal changes, but the changes vary in intensity. So if it’s something relatively complex then internal really requires 2 or if it’s a weird game logic thing like this. The only types of changes that really get through without reviews are CI or things that are so minor or in no way controversial that a review pipeline would just waste time. Like, for example, fixing a typo or something.

**Comment by hakusaro** [comment]
(So, in other words, I place heavy emphasis on “usually”)

**Review by hakusaro — APPROVED** [review]

**Pull request merged**
