### PR TITLE
Remove obsolete resources

### PR DESCRIPTION
**Pull request by Arthri**
PR removes obsolete resource files, because they contain no data and are not referenced by code:
- https://github.com/Pryaxis/TShock/blob/1d4d19f/TShockAPI/Resources.resx
- https://github.com/Pryaxis/TShock/blob/1d4d19f/TShockAPI/Resources.Designer.cs

### CODE REVIEW

**Comment by hakusaro** [comment]
@Arthri can you re-merge this with latest changes since csproj changed?

**Review by hakusaro — CHANGES_REQUESTED** [review]
Due to tshock 5 merges, the csproj now has conflicts -- can you fix conflicts and repush?

**Review by hakusaro — CHANGES_REQUESTED** [review]
I don't think the csproj file changed at all actually. Can you remove that from this commit? The only changes that aren't whitespace are line ending changes or something.

**Comment by Arthri** [comment]
I'll redo the changes in another branch. I can't remove that csproj change because of weird EOL settings

**Pull request closed without merging**
