### PR TITLE
Update Newtonsoft.Json to the latest version (10) Fixes #1526

### LINKED ISSUE #1526: Update json library if possible
If possible, update Newtonsoft's JSON library to the newest version across here and the other API related projects.

### PR DESCRIPTION
**Pull request by Ryozuki**
This PR goes together with the PR in TerrariaAPI-Server (https://github.com/Pryaxis/TerrariaAPI-Server/pull/148)

It should work, i leave here a TShock build with a plugin (Helperbot) i compiled using the new Newtonsoft.Json version.
[TShockJSON.10.zip](https://github.com/Pryaxis/TShock/files/1539818/TShockJSON.10.zip)

It adds a TerrariaServer.exe.config to force it to use Newtonsoft.Json 10

### CODE REVIEW

**Comment by hakusaro** [comment]
konata__seal_of_approval_by_mawscm-d4wm6zi

**Comment by QuiCM** [comment]
I raised some concerns about this in Discord, so will re-raise them here for discussion/prosperity.
If any of my below statements are incorrect, feel free to correct me

* Binding redirects add a layer of misdirection that is not immediately obvious to anyone working on the source.
Say, for example, we some day decide to update to Newtonsoft.Json v12 for some new feature that will ONLY work with v12, and enough time has passed that we forget that we added a binding redirect. Because the redirect force loads v10, we get stuck trying to figure out why - the NuGet version says 12, why is it loading 10??
* I'm not sure why I did dot points, the above is my main argument against using a binding redirect when we can easily upgrade the NuGet package in OTAPI & TShock

**Comment by Ijwu** [comment]
Binding redirects typically only redirect to newer versions.

**Comment by QuiCM** [comment]
In that case will we be adding a new binding redirect for every new version of Newtonsoft, while maintaining a NuGet v9 reference?

**Comment by bartico6** [comment]
Instead of adding a redirection in .config (the .config files fucking suck if you ask me) you can hook the AppDomain assembly resolve event and force the available DLL to load even if the version doesn't match - in that case you're gonna have a fully version-agnostic loading system for this, provided you don't use, say, NJ 10 features while running NJ9. Because that will crash.

**Comment by hakusaro** [comment]
> I'm not sure why I did dot points, the above is my main argument against using a binding redirect when we can easily upgrade the NuGet package in OTAPI & TShock

@QuiCM stupid question: how does one update it in OTAPI?

**Comment by QuiCM** [comment]
@hakusaro it should be a nuget package - update it as you would any other nuget package

**Comment by hakusaro** [comment]
@QuiCM I checked the following ```packages.conf``` files and did not find any Json.

* https://github.com/DeathCradle/Open-Terraria-API/blob/master/OTAPI.Patcher/packages.config
* https://github.com/DeathCradle/Open-Terraria-API/blob/master/OTAPI.Patcher.Engine/packages.config
* https://github.com/DeathCradle/Open-Terraria-API/blob/master/OTAPI.Tests/OTAPI.Tests.Common/packages.config

The [tests area](https://github.com/DeathCradle/Open-Terraria-API/blob/master/OTAPI.Tests/OTAPI.Server.Tests/packages.config) has some Json -- is that the one to update?

**Comment by QuiCM** [comment]
See https://github.com/DeathCradle/Open-Terraria-API/tree/master/OTAPI.Modifications/OTAPI.Modifications.Json

Update the NuGet reference in that project and rerun the patcher

**Comment by hakusaro** [comment]
@QuiCM okay, so can you explain why there's a mismatch between these two versions? Is that negligible?

screen shot 2017-12-07 at 16 51 26

**Comment by hakusaro** [comment]
@QuiCM also, did you mean [this packages.json](https://github.com/DeathCradle/Open-Terraria-API/blob/master/OTAPI.Modifications/OTAPI.Modifications.Json/packages.config) instead? lol

**Comment by QuiCM** [comment]
As per discussion in Discord:
Updating the Newtonsoft NuGet package in the [OTAPI NuGet modification](https://github.com/DeathCradle/Open-Terraria-API/tree/master/OTAPI.Modifications/OTAPI.Modifications.Json) project will update the reference across all of OTAPI

**Comment by hakusaro** [comment]
@QuiCM technically anyone with commit access to OTAPI can also do it.

**Comment by DeathCradle** [comment]
@hakusaro @QuiCM I can try to roll a new nuget version within the next day or so.

@hakusaro Re: .csproj, if I recall correct one of those versions is the assembly version whereas the other is the assembly file version.

**Comment by hakusaro** [comment]
Closing this pull request as a target pull request needs to go to the OTAPI repo, not this repo based on final solution.

**Pull request closed without merging**
