### PR TITLE
Initialize PlayerData on connect

### LINKED ISSUE #1460: NullReferenceException Spam from HandlerGetData / HandlePlayerUpdate
**TShock Version**
4.3.24, APIv2.1, OTAPI v2.0.0.27

**Stack Trace**
> System.NullReferenceException: Object reference not set to an instance of an object.
   at TShockAPI.GetDataHandlers.HandlePlayerUpdate(GetDataHandlerArgs args)
   at TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)

**Reproducibility**
Unfortunately I have been unable to track down the cause or source of the problem. However, I do know that this NRE spams our server's SQL logs significantly (we get on average 8000 to 10000 of these errors reported a day) and in rapid-fire succession. While it doesn't impact the users or the server stability directly, this NRE appears extensively and at random.

**Screenshot**
capture

### PR DESCRIPTION
**Pull request by QuiCM**
This way every player has non-null player data. Should close #1460 
Requires testing

### CODE REVIEW

**Comment by Ijwu** [comment]
Pending testing

**Comment by hakusaro** [comment]
Pending testing?

**Comment by QuiCM** [comment]
yep

**Comment by hakusaro** [comment]
Pending testing?

**Comment by QuiCM** [comment]
Yep

**Pull request merged**
