### PR TITLE
New features in TSPlayer.

### PR DESCRIPTION
**Pull request by AgaSpace**
The ability to set the pvp mode.
Ability to remove buffs.

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
no :(

### CODE REVIEW

**Comment by moisterrific** [comment]
Does this mean buffs can also be banned as long as the server is in SSC?

**Comment by AgaSpace** [comment]
> Does this mean buffs can also be banned as long as the server is in SSC?

You can remove buff from the player, so I think you are right.

**Comment by bartico6** [comment]
The removal of buffs won't work, after you send the `PlayerBuff` packet, the player will lose all buffs.

**Comment by AgaSpace** [comment]
> The removal of buffs won't work, after you send the `PlayerBuff` packet, the player will lose all buffs.

I apologize for my inattention.
Terraria Server does not record buffs.

**Comment by Kojirremer** [comment]
> 
> 
> Does this mean buffs can also be banned as long as the server is in SSC?

The BanBuff plugin gives you the ability to ban (not remove) them in the same way as Itemban, TileBan and ProjBan. It's strict though; it will immediately kick offenders rather than disable them.

imagen

**Comment by bartico6** [comment]
> 
> 
> > The removal of buffs won't work, after you send the `PlayerBuff` packet, the player will lose all buffs.
> 
> I apologize for my inattention.
> Terraria Server does not record buffs.

You can keep the PvP status part, though - that one looks good and should work :-)

**Pull request closed without merging**
