### PR TITLE
Update SQlite

### PR DESCRIPTION
**Pull request by Ryozuki**
Updated sqlite3.dll (from 3.8.9 to 3.23.1) and Mono.Data.Sqlite.dll (from an unknown old version to 1.0.61)

### CODE REVIEW

**Comment by QuiCM** [comment]
Hi
* You have a merge conflict to fix
* Does this cause any regressions with older databases?
Otherwise looks good, if you can fix the conflict and confirm there's no regressions I'll be happy to merge

**Comment by Ryozuki** [comment]
I don't think it causes regression with older databases.

**Comment by Ijwu** [comment]
You think it's compatible or you tested it with older database and are sure it's compatible?

**Comment by DankRank** [comment]
Sqlite devs maintain backwards compatibility with every prior release of sqlite3. Considering how much testing they do before release, and how widely sqlite3 is used, it's extremely unlikely that there's an incompatibility bug.

**Comment by QuiCM** [comment]
That doesn't negate the need to test

**Comment by hakusaro** [comment]
I would actually consider sqlite3 to be 100% fine for merging -- but the Mono version I'm curious about.

(Sqlite3 -- the C driver -- is ridiculously well tested -- to the point of being almost legendary).

**Comment by Ijwu** [comment]
The PR title notes WIP. I'm not merging while this is WIP. If this is complete please edit.

Otherwise, we do expect some semblance of a test plan for PRs. Since, I assume, you did some amount of initial testing and have determined it's good enough please outline your test plan or test cases. Just a quick summary of "tested on XYZ operating system using XYZ version of OS with a pre-existing/new sqlite database".

Give us some amount of comfort that this is as solid as you say it is other than 

>...I'm not going to test this deeply, i haven't got the time to do so.

**Comment by hakusaro** [comment]
@Ryozuki ping?

**Comment by hakusaro** [comment]
Removing the WIP tag since I don't think this is WIP anymore.

**Comment by Ijwu** [comment]
I'm fine with merging this, given someone with a Mono based system can thumbs up it. 

For future reference, @Ryozuki, you've only done extremely basic testing. We expect some more effort to show that you've attempted to cover all the test cases you can reasonably cover. Starting a new database and adding a user and warps is a good start. But there's a dozen more test cases that overlooks. All of which you can check within a reasonable amount of time on your system.

I hate to say this as an absolute, but it will only serve you well in software development: if you haven't got the time to test then you haven't got the time to develop. Testing your own changes as if you're your own QA is necessary as a software developer. Trust me, it will only help and save headache.

**Comment by Ryozuki** [comment]
Tbh i wouldn't call replacing libraries "developing", also there is no comparison between the time needed to replace them to  the time i would spent testing this.

Also a good software project would have some kind of test framework, which from what i know tshock lacks.

**Comment by QuiCM** [comment]
Still awaiting mono testing

**Comment by DankRank** [comment]
I'll try to test this on mono today. I have a database from stable version.

**Comment by Ijwu** [comment]
You're making changes to a software project by updating source code. You are developing. 

I honestly can't see testing this, even on Mono, to take longer than 1 hour total. Even if I included the time it would take to spin up a linux VM on a cloud service provider. 

I also don't see it taking much more than an hour or so to develop this and make a PR.

The time developing it and testing it is very comparable. You clearly had the time to develop it. 

It's my job to steward changes to the project. I just want to ensure everything going in is definitely going to work. You never know when that one thing that "is probably fine" isn't fine. When that's the case the TShock team has to deal with the consequences.

**Comment by DankRank** [comment]
1) Copied my sqlite db from stable server
2) Compiled as release, crashed:
```
2018-05-08 16:38:55 - TShock: ERROR: Fatal Startup Exception
2018-05-08 16:38:55 - TShock: ERROR: Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
unrecognized token: "5Bp1eMoW8yqLmAAeJT0D_Bans"
  at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x001f8] in <9b5a3bbbcb764995bb893ef8f1f8c827>:0 
  at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x000d3] in <9b5a3bbbcb764995bb893ef8f1f8c827>:0 
  at Mono.Data.Sqlite.SqliteCommand.GetStatement (System.Int32 index) [0x00008] in <9b5a3bbbcb764995bb893ef8f1f8c827>:0 
  at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteCommand.GetStatement(int)
  at Mono.Data.Sqlite.SqliteDataReader.NextResult () [0x000b3] in <9b5a3bbbcb764995bb893ef8f1f8c827>:0 
  at Mono.Data.Sqlite.SqliteDataReader..ctor (Mono.Data.Sqlite.SqliteCommand cmd, System.Data.CommandBehavior behave) [0x0004e] in <9b5a3bbbcb764995bb893ef8f1f8c827>:0 
  at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteDataReader..ctor(Mono.Data.Sqlite.SqliteCommand,System.Data.CommandBehavior)
  at Mono.Data.Sqlite.SqliteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00006] in <9b5a3bbbcb764995bb893ef8f1f8c827>:0 
  at Mono.Data.Sqlite.SqliteCommand.ExecuteNonQuery () [0x00000] in <9b5a3bbbcb764995bb893ef8f1f8c827>:0 
  at TShockAPI.DB.DbExt.Query (System.Data.IDbConnection olddb, System.String query, System.Object[] args) [0x00043] in <ec9a6a7b5aa4432b95f33dfcbecacca1>:0 
  at TShockAPI.DB.SqlTableCreator.EnsureTableStructure (TShockAPI.DB.SqlTable table) [0x000c2] in <ec9a6a7b5aa4432b95f33dfcbecacca1>:0 
  at TShockAPI.DB.BanManager..ctor (System.Data.IDbConnection db) [0x000dc] in <ec9a6a7b5aa4432b95f33dfcbecacca1>:0 
  at TShockAPI.TShock.Initialize () [0x0039a] in <ec9a6a7b5aa4432b95f33dfcbecacca1>:0 
```
3) Ran it two more times, same result, except unrecognized tokens had slightly different names: `1l4dKX1YVKe0UR88BiKM_Bans` and `83NO82eSye9ZIXbbx08D_Bans`
4) Compiled as debug, it started up normally
5) Tried release version again (same binaries as in step 2), it started up normally
6) Copied over stable sqlite db again, it started up normally. (Couldn't reproduce the crash during step 2)
7) Joined server. SSC works.
8) Realized I still had PDB from debug version. `rm ServerPlugins/TShockAPI.pdb`. Crash reproduced.
9) Copied over the release PDB, no crash.
10) Deleted PDB again, no crash :thinking: 
11) Copied stable database over yet again, no crash. Can't reproduce it now :thinking: :thinking: :thinking:

**Comment by hakusaro** [comment]
Well, that's depressing. Thanks for your testing @DankRank.

**Comment by hakusaro** [comment]
I'm going to go-ahead and say that this needs more testing before we can actually sign-off on merging. The stack trace that @DankRank posted needs to be investigated too.

**Comment by Ryozuki** [comment]
:)

**Pull request closed without merging**
