### PR TITLE
Turn the player hooks into a tristate #1470

### PR DESCRIPTION
**Pull request by deadsurgeon42**
https://github.com/Pryaxis/TShock/issues/1470
This adds a  new `PermissionResult` enum with 3 values that specify allowed, denied and unknown, which "unknown" means tshock should do the check.

### CODE REVIEW

**Comment by deadsurgeon42** [comment]
@QuiCM okay, 
@ProfessorXZ they do work the same, like
`ask hook -> allow/block item use -> if inconclusive check group/tempgroup`

**Comment by ProfessorXZ** [comment]
Ok, I failed to see the database managers. The PR is still missing a changelog update nonetheless.

**Comment by deadsurgeon42** [comment]
@Enerdy maybe rename the enum to `PermissionHookResult` and `Inconclusive` to `Unhandled`?

**Comment by Enerdy** [comment]
`PermissionHookResult` feels slightly superfluous there, although it does clarify what the enum is for. I'll leave that one up to you.

And yes, lets not leave this issue in an inconclusive state -- no one would want that.

**Pull request merged**
