### PR TITLE
Separate out region related code

### LINKED ISSUE #1564: Subsystem Isolation: Regions
In similar fashion to #1560, we need to isolate the regions system and related code and hooks into a subsystem like Bouncer. More information can be found in #1563 on what specifics probably need to happen.

### PR DESCRIPTION
**Pull request by ivanbiljan**
Similar to what has been done in #1560, this pull request aims to isolate region related logic by moving everything into a separate subsystem. Fixes #1564

### CODE REVIEW

**Comment by ivanbiljan** [comment]
The requested changes have been applied and put to test. Everything seems to work as intended after replacing `ServerApi.Hooks.GameUpdate` with `GetDataHandlers.PlayerUpdate` (the hook also does fire when teleportation items are used).

**Comment by hakusaro** [comment]
> This branch is out-of-date with the base branch
> Merge the latest changes from general-devel into this branch.

**Comment by hakusaro** [comment]
Disregard that commit is stupid. I'll get right on re-reviewing.

**Comment by Ijwu** [comment]
LGTM too. Merging and closing.

**Pull request merged**
