### PR TITLE
Update for Terraria 1.4.3.4

### PR DESCRIPTION
**Pull request by Patrikkk**
I've decided to use the `DebugCommand` entity source for anything server related, as it makes the most sense as source. Feel free to discuss.
Running 1.4.3.4 stable on Aurora. First waiting for OTAPI to be updated on nuget, then TSAPI has to be accepted and updated to the nuget ref. Then this can be accepted and the terrariaserver submodule updated.

### CODE REVIEW

**Comment by drunderscore** [comment]
Any fears it would be removed by ReLogic in the future? I doubt it, but should we create our own source?

**Comment by SignatureBeef** [comment]
> First waiting for OTAPI to be updated on nuget

its up: https://www.nuget.org/packages/OTAPI/2.0.0.48

**Review by QuiCM — DISMISSED** [review]
Debug command sounds fine for now, can maybe move to our own later on it if provides us anything worthwhile

**Comment by hakusaro** [comment]
@QuiCM, I've updated this branch to reference the new OTAPI version (2.0.0.48) via updating to point to https://github.com/Pryaxis/TSAPI/commit/91e94388f15bd9b40786e052ef1a06173830b09d. This just included missing version numbers because the update wasn't complete in the previous PR. I've also updated general-devel on this repo to downgrade to the github actions runner for windows server 2019, which fixes the build failure, and updated this branch with those changes. So if you want to approve, you can now.

I can handle the release for the next version + increment + etc if you're good with that after.

**Review by QuiCM — APPROVED** [review]

**Pull request merged**
