### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by cardinal-system**

### CODE REVIEW

**Comment by EMREOYUN** [comment]
Can we add the Turkish language as well? I'm willing to translate.

**Comment by hakusaro** [comment]
@EMREOYUN yes!

**Comment by hakusaro** [comment]
@EMREOYUN it's gonna take a bit of time to get more and more of the strings in the file. I appreciate your work so far!

**Comment by EMREOYUN** [comment]
> @EMREOYUN it's gonna take a bit of time to get more and more of the strings in the file. I appreciate your work so far!

We are getting notifications from the project. I'll check it out when added.

**Pull request merged**
