### PR TITLE
Cleanup SaveManager

### PR DESCRIPTION
**Pull request by MarioE**
We don't really need to have a separate thread that constantly polls for saves. While this new Task-based method does not completely replicate the old approach, it shouldn't really matter as the saves executing "out of order" does not matter.

### CODE REVIEW

**Comment by tylerjwatson** [comment]
Be wary that the waiting needs to happen in *some* thread, and in my opinion it should be on a separate Thread as was originally designed.  The issue I find with this Task`-based solution is using ThreadPool for background-based spinning, which is not a good use of the limited pool of threads.  The main use of the threadpool is for little tasks that do not justify creation of new threads as thread creation is expensive.  Since SaveManager runs for the lifetime of the application, it should rightfully be in its own thread, in my opinion.

**Comment by MarioE** [comment]
Do we even need to wait, though? What's the point of having a separate thread if we just wait all the time? We might as well synchronously run it on the main thread. It's not like saving takes that long, tbh.

**Comment by tylerjwatson** [comment]
Becuase the main thread has a game timer that needs to tick at 60 fps, or 16.667ms. Unless the save fits comfortably in that time (with leaving room for all the update hooks to run) then I'm not okay with it.  

I mean, I don't control the project, but merging it would be against my advice.

**Comment by MarioE** [comment]
The thing is, though, it already blocks for most occurrences of saves.

**Comment by tylerjwatson** [comment]
It does? Then what's the purpose of the thread?

**Comment by MarioE** [comment]
Beats me; I left in the `wait` parameter to preserve compatibility. Otherwise I would've switched to a fire-and-forget sort of thing entirely

**Comment by hakusaro** [comment]
Hi @MarioE @tylerjwatson what's up with this PR?

**Pull request closed without merging**
