### PR TITLE
Add more HintPaths for OTAPI

### PR DESCRIPTION
**Pull request by Leeleo3x**
This will help msbuild to find missing libraries when create release
with `/p:Configuration=Release`.

With this patch, the searching order will be:
  - If OTAPI with same configuration found, use that.
  - Else if OTAPI with Release configuration found, use that.
  - Else use OTAPI with Debug configuration.

This will fix the issue #1480

### CODE REVIEW

**Comment by Leeleo3x** [comment]
Close by mistake. Sorry for the noise.

**Comment by hakusaro** [comment]
Note AppVeyor: https://ci.appveyor.com/project/hakusaro/tshock/build/68

**Comment by Leeleo3x** [comment]
Right, it will check if Release folder exists or not. If not it will pick OTAPI in Debug folder.

**Comment by ProfessorXZ** [comment]
@Leeleo3x @hakusaro status?

**Comment by hakusaro** [comment]
@ProfessorXZ I'm not experienced enough in this domain to be able to approve it. I wish I could provide more feedback.

**Comment by hakusaro** [comment]
@Pryaxis/tshock can someone with more experience than me look into this issue?

**Comment by tylerjwatson** [comment]
Pending no objections (and me actually remembering) i'll merge this in later.

**Pull request merged**
