### PR TITLE
REST Server Broadcast Permission

### PR DESCRIPTION
**Pull request by TheBambino**
**Feature Request:**
If a REST token is breached, there could be potential spam issues. Where each token perm could pose a potential risk, not having perms on ServerBroadcast makes it an issue if **any** token is breached.

### CODE REVIEW

**Comment by bartico6** [comment]
You might need to recreate the pull request - you published your own server's modifications to join messages (and name coloring, too). You seem to have also started the PR before merging upstream changes to your branch.

**Comment by TheBambino** [comment]
First time to do a PR. I knew something didn't look right.

**Comment by bartico6** [comment]
You should use branches more often, that will prevent things like accidental code disclosure if you separate things you're adding (and merge them into main once they're ready).

Ideally if you use one repo for committing to here and the same repo for your private fork, keep your private modifications on a branch named after your server, so that you can always rebase your branch to the new commits from main and so that you can create new branches off of it to easily submit PRs.

**Comment by TheBambino** [comment]
Thanks. Makes sense. I thought a PR could be done on a commit basis.

**Pull request closed without merging**
